version: '3.4'

services:
  catalogdb:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
  basketdb:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discount.db
    environment:
      - POSTGRES_USER=postgres #Be carful to do not add any whitespace after =
      - POSTGRES_PASSWORD=postgres1993
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    restart: always
    ports:
      - "5432:5432"
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "saidben1993"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
 
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com #Be carful to do not add any whitespace after =
      - PGADMIN_DEFAULT_PASSWORD=admin1993 #if you add any changes to your code if you can not connect to postgres using pgadmin then try docker-compose down --volume
    volumes:
      - pgadmin_data:/root/.pgadmin
    restart: always
    ports:
      - "5050:80"
   
          
    
  catalog.api:
    container_name: catalog.api
  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: besket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc" #add http:// or you would get an exeption

    depends_on:
      - basketdb

    ports:
      - "8001:80"


  discount.api:
    container_name: discount.api

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=postgres;Password=postgres1993;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=postgres;Password=postgres1993;"

    depends_on:
      - discountdb
    ports:
      - "8003:80"
